### PR TITLE
Imported docs from bridge 3

### PR DESCRIPTION
**Pull request by pvgenuchten**
imported docs from bridge 3
still need to make esri references more generic (bridge used to be esri only)
creating this to facilitate discussion, for example: is this a proper place for this docs, or should we create a separate repository, since we target this plugin, but also the arcmap and arcpro plugin

### CODE REVIEW

**Comment by pvgenuchten** [comment]
the code was imported from rst with some automatic conversion, but seems tables are messed up

**Comment by MichelGabriel** [comment]
> but seems tables are messed up

Yes, the tables are done the way Github likes it

**Comment by MichelGabriel** [comment]
If we use VuePress everything will look good :-)

**Comment by pvgenuchten** [comment]
fixed the tables by introducing another sphinx plugin. would be interested to see how vuepress renders these markdown documents

**Pull request merged**
